### 회원가입 -성공
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "최승환",
  "username": "test@naver.com",
  "password": "test1234",
  "nickname": "안양개발자"
}

### 회원가입 - 실패
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "김민지",
  "username": "test1@naver.com",
  "password": "test1234",
  "nickname": "안양개발자"
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "test@naver.com",
  "password": "test1234"
}

### 로그아웃
POST http://localhost:8080/api/auth/logout
Authorization: Bearer (access토큰 갖다 붙여넣으면 됨)
