### 1. 회원가입 - 실패 (이메일 인증 안 한 상태로 시도)
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "최승환",
  "username": "이메일_인증_받을_이메일",
  "password": "test1234",
  "nickname": "안양개발자",
  "termsAgreed": true
}

### 2. 이메일 인증코드 발송 -자신의 진짜 이메일 입력(구글,네이버 등등)
POST http://localhost:8080/api/auth/email/send
Content-Type: application/json

{
  "email": "이메일_인증_받을_이메일"
}

### 3. 이메일 인증코드 검증 (메일함에서 받은 코드로 교체)
POST http://localhost:8080/api/auth/email/verify
Content-Type: application/json

{
  "email": "이메일_인증_받을_이메일",
  "code": "452358"
}

### 4. 회원가입 - 성공 (인증 완료 후 재시도)
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "최승환",
  "username": "이메일_인증_완료한_이메일",
  "nickname": "안양개발자",
  "password": "test1234",
  "termsAgreed": true
}

###  같은 이메일로 일반 회원가입 - 성공 (통합연결) - 비밀번호만 넣어줌, 이름과 닉네임은 아무값넣어도 변경안됨
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "최승환",
  "username": "이메일_인증_완료한_이메일이_소셜로그인과_동일한_이메일",
  "nickname": "새닉네임123",
  "password": "test1234",
  "termsAgreed": true
}


### 회원가입 - 실패: username 중복 (409)
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "최승환",
  "username": "중복_이메일",
  "password": "test1234",
  "nickname": "안양원펀치"
}

###  회원가입 - 실패 (약관 동의 안 함)
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "테스트유저",
  "username": "termstest@naver.com",
  "nickname": "약관테스트",
  "password": "test1234",
  "termsAgreed": false
}

### 회원가입 - 실패: nickname 중복 (409)
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "최승환",
  "username": "중복_되지_않은_이메일",
  "password": "test1234",
  "nickname": "안양개발자",
  "termsAgreed": true
}

### 회원가입 - 실패: 이메일 형식 오류 (400)
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "최승환",
  "username": "oh-yeah",
  "password": "test1234",
  "nickname": "안양인",
  "termsAgreed": true
}

### 회원가입 - 실패: 비밀번호 8자미만 (400)
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "최승환",
  "username": "중복_되지_않는_이메일",
  "password": "1234",
  "nickname": "안양인",
  "termsAgreed": true
}

### 회원가입 - 실패: 필수값 누락 (400)
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "",
  "username": "test@naver.com",
  "password": "test1234",
  "nickname": "새닉네임3",
  "termsAgreed": true
}

### 로그인 - 성공 (200)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "회원가입_완료된_이메일",
  "password": "test1234"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
%}

### 로그인 - 실패: 존재하지 않는 계정 (404)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "non-exist@naver.com",
  "password": "test1234"
}

### 로그인 - 실패: 비밀번호 불일치 (401)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "회원가입_완료된_이메일",
  "password": "test5555"
}


### 로그아웃 - 성공 (200)
POST http://localhost:8080/api/auth/logout
Authorization: Bearer {{accessToken}}

### 재발급 성공 (200) / 재발급 - 실패: 쿠키 없음 (400)-(로그아웃하고 실행)
POST http://localhost:8080/api/auth/reissue


### 비밀번호 재설정 테스트


### 비밀번호 재설정 - 실패 (이메일 인증 안 한 상태)
POST http://localhost:8080/api/auth/reset-password
Content-Type: application/json

{
  "username": "이메일_인증_안된_이메일",
  "newPassword": "newpw1234"
}

### 이메일 인증코드 발송
POST http://localhost:8080/api/auth/email/send
Content-Type: application/json

{
  "email": "이메일_인증_받을_이메일"
}

### 이메일 인증코드 검증 (메일함에서 받은 코드로 교체)
POST http://localhost:8080/api/auth/email/verify
Content-Type: application/json

{
  "email": "이메일_인증_받을_이메일",
  "code": "511318"
}

### 비밀번호 재설정 - 성공 (인증 완료 후)
POST http://localhost:8080/api/auth/resetpassword
Content-Type: application/json

{
  "username": "이메일_인증_완료된_이메일",
  "newPassword": "newpw1234"
}

### 비밀번호 재설정 - 실패 (방금 그 인증기록으로 또 재설정 시도, 소비됐는지 확인!)
POST http://localhost:8080/api/auth/resetpassword
Content-Type: application/json

{
  "username": "이메일_인증_완료된_이메일",
  "newPassword": "anotherpw1234"
}
