### 로그인 - 성공 (200) 이건 Admin 계정만 로그인해야됩니다. 각자 로컬에서 수동으로 쿼리문 작성해서 admin 설정하고 로그인 해서 테스트해주시면됩니다다.
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "csh980930@naver.com",
  "password": "test1234"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
%}

###  전체 조회 (검색/필터 없음)
GET http://localhost:8080/api/admin/users
Authorization: Bearer {{accessToken}}

###  닉네임으로 검색
GET http://localhost:8080/api/admin/users?keyword=안양
Authorization: Bearer {{accessToken}}

###  이메일로 검색
GET http://localhost:8080/api/admin/users?keyword=csh9809@hufs.ac.kr
Authorization: Bearer {{accessToken}}

###  role 필터만 적용 (EXPERT만 보기)
GET http://localhost:8080/api/admin/users?role=EXPERT
Authorization: Bearer {{accessToken}}

###  검색어 + role 필터 동시 적용
GET http://localhost:8080/api/admin/users?keyword=gmail&role=USER
Authorization: Bearer {{accessToken}}

###  검색 결과 없음 (존재하지 않는 키워드)
GET http://localhost:8080/api/admin/users?keyword=존재하지않는이상한값
Authorization: Bearer {{accessToken}}

###  페이징과 같이 사용
GET http://localhost:8080/api/admin/users?keyword=테스트&page=0&size=5
Authorization: Bearer {{accessToken}}

### 유저 상태 변경 - 성공 (SUSPENDED)
PATCH http://localhost:8080/api/admin/users/4/status
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "status": "SUSPENDED"
}

### 유저 상태 변경 - 실패: WITHDRAWN 시도 (400) withdrawn은 사용자 자신이 판단해서 회원탈퇴하기로!! admin이 사용자를 탈퇴시킬순없다.
PATCH http://localhost:8080/api/admin/users/4/status
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "status": "WITHDRAWN"
}

### 유저 상태 변경 - 실패: 없는 id (404)
PATCH http://localhost:8080/api/admin/users/99999/status
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "status": "ACTIVE"
}


### 게시글 강제 삭제 - 성공 (ADMIN)
DELETE http://localhost:8080/api/admin/posts/1
Authorization: Bearer {{accessToken}}

### 게시글 강제 삭제 - 실패: 없는 id (404)
DELETE http://localhost:8080/api/admin/posts/99999
Authorization: Bearer {{accessToken}}

### 게시글 강제 삭제 - 실패: ADMIN 아님 (403) 일반유저로 로그인해서 테스트
DELETE http://localhost:8080/api/admin/posts/2
Authorization: Bearer {{accessToken}}

### 댓글 강제 삭제 - 성공 (ADMIN)
DELETE http://localhost:8080/api/admin/comments/1
Authorization: Bearer {{accessToken}}

### 댓글 강제 삭제 - 실패: 없는 id (404)
DELETE http://localhost:8080/api/admin/comments/99999
Authorization: Bearer {{accessToken}}

### 댓글 강제 삭제 - 실패: ADMIN 아님 (403)
DELETE http://localhost:8080/api/admin/comments/1
Authorization: Bearer {{accessToken}}

### 스터디 강제 삭제 - 성공 (ADMIN)
DELETE http://localhost:8080/api/admin/studies/2
Authorization: Bearer {{accessToken}}

### 스터디 강제 삭제 - 실패: 없는 id (404)
DELETE http://localhost:8080/api/admin/studies/99999
Authorization: Bearer {{accessToken}}

### 스터디 강제 삭제 - 실패: ADMIN 아님 (403)
DELETE http://localhost:8080/api/admin/studies/1
Authorization: Bearer {{accessToken}}

### 스터디 게시글 강제 삭제 - 성공 (ADMIN, 댓글 있어도 됨)
DELETE http://localhost:8080/api/admin/study-posts/1
Authorization: Bearer {{accessToken}}

### 스터디 게시글 강제 삭제 - 실패: 없는 id (404)
DELETE http://localhost:8080/api/admin/study-posts/99999
Authorization: Bearer {{accessToken}}

### 스터디 게시글 강제 삭제 - 실패: ADMIN 아님 (403)
DELETE http://localhost:8080/api/admin/study-posts/1
Authorization: Bearer {{accessToken}}

### 스터디 게시글 댓글 강제 삭제 - 성공 (ADMIN)
DELETE http://localhost:8080/api/admin/study-post-comments/1
Authorization: Bearer {{accessToken}}

### 스터디 게시글 댓글 강제 삭제 - 실패: 없는 id (404)
DELETE http://localhost:8080/api/admin/study-post-comments/99999
Authorization: Bearer {{accessToken}}

### 스터디 게시글 댓글 강제 삭제 - 실패: ADMIN 아님 (403)
DELETE http://localhost:8080/api/admin/study-post-comments/1
Authorization: Bearer {{accessToken}}