spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/prep2getherdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org:
      springframework:
        security: trace

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000        # 1시간 (밀리초)
  refresh-token-expiration: 1209600000    # 14일 (밀리초)